services:
  postgres-db:
    env_file:
      - .env
    build:
      context: ./etc/postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - py-react-kit

  python-web-server:
    build:
      context: .
    container_name: python-web-server
    ports:
      - "8080:8080"
    volumes:
      - .:/app,rw
    networks:
      - py-react-kit

  adminer:
    image: adminer:4-standalone
    container_name: adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - py-react-kit

networks:
  py-react-kit:
    name: py-react-kit

volumes:
  dbdata:
    driver: local